package db.constants.mySQL;

public enum Queries {

    ALL_VIEWS("SHOW FULL TABLES WHERE table_type = 'VIEW'"),
    ALL_TABLES("SHOW FULL TABLES WHERE table_type = 'BASE TABLE'"),
    ALL_COLUMNS("SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ="),
    COLUMN_INFO("SHOW FULL COLUMNS FROM "),
    INDEX_LAZY_LOAD("SELECT INDEX_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND INDEX_NAME != 'PRIMARY' GROUP BY INDEX_NAME"),
    ALL_INDEX_INFO("SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND INDEX_NAME != 'PRIMARY' GROUP BY INDEX_NAME"),
    TRIGGERS_LAZY_LOAD(
            "SELECT TRIGGER_NAME FROM INFORMATION_SCHEMA.TRIGGERS WHERE INFORMATION_SCHEMA.TRIGGERS.TRIGGER_SCHEMA = ? AND EVENT_OBJECT_TABLE = ?"),
    ALL_TRIGGERS_INFO(
            "SELECT * FROM INFORMATION_SCHEMA.TRIGGERS WHERE INFORMATION_SCHEMA.TRIGGERS.TRIGGER_SCHEMA = ? AND EVENT_OBJECT_TABLE = ?"),
    ALL_PROCEDURE_INFO("SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_TYPE = 'PROCEDURE'"),
    DETAIL_PROCEDURE_INFO("SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_NAME = ?"),
    ALL_FUNCTION_INFO("SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_TYPE = 'FUNCTION'"),
    DETAIL_FUNCTION_INFO("SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_TYPE = 'FUNCTION' AND ROUTINE_NAME = ?"),
    ALL_PRIMARY_KEY_INFO(
            "SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS T  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE K USING(CONSTRAINT_NAME,TABLE_SCHEMA,TABLE_NAME) WHERE T.CONSTRAINT_TYPE='PRIMARY KEY' AND T.TABLE_SCHEMA= ?  AND T.TABLE_NAME = ?"),
    PRIMARY_KEY_LAZY_LOAD(
            "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS T  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE" +
                    " K USING(CONSTRAINT_NAME,TABLE_SCHEMA,TABLE_NAME) WHERE T.CONSTRAINT_TYPE='PRIMARY KEY' AND T.TABLE_SCHEMA= ?  AND T.TABLE_NAME = ?"),
    FOREIGN_KEY_LAZY_LOAD("SELECT  A.CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE A, " +
            "INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS B WHERE A.CONSTRAINT_SCHEMA =" +
            "                       ? AND A.TABLE_NAME = ? AND A.REFERENCED_TABLE_NAME " +
            "IS NOT NULL AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME"),
    ALL_FOREIGN_KEY_INFO("SELECT COLUMN_NAME AS ENTITY_NAME, A.CONSTRAINT_SCHEMA AS SCHEMA_NAME, A.CONSTRAINT_CATALOG,  " +
            "A.TABLE_NAME AS TABLE_NAME, A.CONSTRAINT_NAME, A.TABLE_CATALOG, A.ORDINAL_POSITION, A.POSITION_IN_UNIQUE_CONSTRAINT, A.REFERENCED_TABLE_SCHEMA, " +
            "A.REFERENCED_TABLE_NAME, A.REFERENCED_COLUMN_NAME, B.DELETE_RULE, B.UPDATE_RULE FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE A, " +
            "INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS B WHERE A.CONSTRAINT_SCHEMA = ? AND A.TABLE_NAME = ? AND A.REFERENCED_TABLE_NAME " +
            "IS NOT NULL AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME");

    private String value;

    private Queries(String s) {
        this.value = s;
    }

    public String get() {
        return value;
    }
}
